services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - vi_trucking_db

  vi_trucking_db:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vi_trucking
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: